name: 'Purge Pull Requests'

on:
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          close-pr: true
          lock-pr: true
          pr-lock-reason: 'This repository does not support Pull Requests. If you have a feature you would like to be added, please open an issue.'
          process_only: 'prs'
          log-output: false
